### ISSUE TITLE
Usage instructions?

### ISSUE THREAD

**Issue by MiniCodeMonkey** [Raynes/udder#7]
Hey,

This looks like a neat project. Can you please add some quick usage instructions? I would love to have a go at it.

**Comment by Raynes** [comment]
Hey there! Awesome someone's already found this. Myself and my roommate have been working on this as a side project. I've got a lot of really cool ideas for it and I'm working on productizing and releasing over this weekend. Check back by Sunday evening and things will be in much better shape!

**Comment by MiniCodeMonkey** [comment]
Cool! Thanks for the quick reply.

I can see that you're working on an Alexa app to control the Hue lights, looks pretty sweet. What I'm working on is over here: https://github.com/hjem/hjem-alexa

**Comment by Raynes** [comment]
Alrighty, good to go. Released 0.1.0 with the utterance generator. Hoping to do more!
